### ISSUE TITLE
ValueError: Input y_pred contains NaN.

### ISSUE THREAD

**Issue by wangyihan1128** [XpastaX/ConFEDE#15]
ValueError: Input y_pred contains NaN.

当我的模型在输出预测结果的时候会出现无效值，这是为什么？谢谢

**Comment by XpastaX** [comment]
请提供下具体报错信息。可以先检查一下python环境是否一致。

**Comment by pangzhongpeng** [comment]
/home/user_3/.local/lib/python3.8/site-packages/torch/nn/modules/transformer.py:282: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")
Epoch:1|Loss:[tensor(nan, device='cuda:0', grad_fn=<MseLossBackward0>)]|: 100%|██████████| 22/22 [00:00<00:00, 37.24it/s]
/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/_array_api.py:245: RuntimeWarning: invalid value encountered in cast
  return x.astype(dtype, copy=copy, casting=casting)
Traceback (most recent call last):
  File "/home/user_3/code/SIMS_bushu/main.py", line 22, in <module>
    Vtrain(check={'MAE':10000}, config=config)
  File "/home/user_3/code/SIMS_bushu/train/constrastive/Vtrain.py", line 76, in Vtrain
    result, result_loss = eval(model, metrics, train_data, device, config)
  File "/home/user_3/code/SIMS_bushu/train/constrastive/Vtrain.py", line 125, in eval
    eval_results = metrics.eval_sims_regression(truth, pred)
  File "/home/user_3/code/SIMS_bushu/util/metrics.py", line 255, in eval_sims_regression
    f_score = f1_score(test_truth_a2, test_preds_a2, average='weighted')
  File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 1239, in f1_score
    return fbeta_score(
  File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 187, in wrapper
    return func(*args, **kwargs)
  File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 1413, in fbeta_score
    _, _, f, _ = precision_recall_fscore_support(
  File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 187, in wrapper
    return func(*args, **kwargs)
  File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 1724, in precision_recall_fscore_support
    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)
  File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 1501, in _check_set_wise_labels
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 86, in _check_targets
    type_pred = type_of_target(y_pred, input_name="y_pred")
  File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 383, in type_of_target
    _assert_all_finite(data, input_name=input_name)
  File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/validation.py", line 122, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/validation.py", line 171, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input y_pred contains NaN.
你好，我在跑SMIS模型的时候遇到同样的问题，我该怎样去解决，这个是sklearn包的问题吗，我用的sklearn版本是1.3.2

**Comment by pppz2024** [comment]
/home/user_3/.local/lib/python3.8/site-packages/torch/nn/modules/transformer.py:282: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")
Epoch:1|Loss:[tensor(nan, device='cuda:0', grad_fn=)]|: 100%|██████████| 22/22 [00:00<00:00, 37.24it/s]
/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/_array_api.py:245: RuntimeWarning: invalid value encountered in cast
return x.astype(dtype, copy=copy, casting=casting)
Traceback (most recent call last):
File "/home/user_3/code/SIMS_bushu/main.py", line 22, in
Vtrain(check={'MAE':10000}, config=config)
File "/home/user_3/code/SIMS_bushu/train/constrastive/Vtrain.py", line 76, in Vtrain
result, result_loss = eval(model, metrics, train_data, device, config)
File "/home/user_3/code/SIMS_bushu/train/constrastive/Vtrain.py", line 125, in eval
eval_results = metrics.eval_sims_regression(truth, pred)
File "/home/user_3/code/SIMS_bushu/util/metrics.py", line 255, in eval_sims_regression
f_score = f1_score(test_truth_a2, test_preds_a2, average='weighted')
File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 214, in wrapper
return func(*args, **kwargs)
File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 1239, in f1_score
return fbeta_score(
File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 187, in wrapper
return func(*args, **kwargs)
File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 1413, in fbeta_score
_, _, f, _ = precision_recall_fscore_support(
File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 187, in wrapper
return func(*args, **kwargs)
File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 1724, in precision_recall_fscore_support
labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)
File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 1501, in _check_set_wise_labels
y_type, y_true, y_pred = _check_targets(y_true, y_pred)
File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 86, in _check_targets
type_pred = type_of_target(y_pred, input_name="y_pred")
File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 383, in type_of_target
_assert_all_finite(data, input_name=input_name)
File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/validation.py", line 122, in _assert_all_finite
_assert_all_finite_element_wise(
File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/validation.py", line 171, in _assert_all_finite_element_wise
raise ValueError(msg_err)
ValueError: Input y_pred contains NaN.
你好，我在跑SMIS模型的时候遇到同样的问题，我该怎样去解决，这个是sklearn包的问题吗，我用的sklearn版本是1.3.2

**Comment by XpastaX** [comment]
@pppz2024 
你的log中有“Epoch:1|Loss:[tensor(nan, device='cuda:0', grad_fn=)”
可能是训练不稳定导致loss出现nan，这种情况我在实验时没有出现。大概率是版本差异。

1. 可以看看transformer,torch 等关乎模型训练的模块版本是否一致。我在训练时没有出现log中的warning： “enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")”
2. 换一个seed 重新训练
3. 尝试减小learning rate
4. 将data size 限制在 10，观察小数据集上有没有问题。

**Comment by XpastaX** [comment]
> /home/user_3/.local/lib/python3.8/site-packages/torch/nn/modules/transformer.py:282: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance) warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}") Epoch:1|Loss:[tensor(nan, device='cuda:0', grad_fn=)]|: 100%|██████████| 22/22 [00:00<00:00, 37.24it/s] /home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/_array_api.py:245: RuntimeWarning: invalid value encountered in cast return x.astype(dtype, copy=copy, casting=casting) Traceback (most recent call last): File "/home/user_3/code/SIMS_bushu/main.py", line 22, in Vtrain(check={'MAE':10000}, config=config) File "/home/user_3/code/SIMS_bushu/train/constrastive/Vtrain.py", line 76, in Vtrain result, result_loss = eval(model, metrics, train_data, device, config) File "/home/user_3/code/SIMS_bushu/train/constrastive/Vtrain.py", line 125, in eval eval_results = metrics.eval_sims_regression(truth, pred) File "/home/user_3/code/SIMS_bushu/util/metrics.py", line 255, in eval_sims_regression f_score = f1_score(test_truth_a2, test_preds_a2, average='weighted') File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 214, in wrapper return func(*args, **kwargs) File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 1239, in f1_score return fbeta_score( File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 187, in wrapper return func(*args, **kwargs) File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 1413, in fbeta_score _, _, f, _ = precision_recall_fscore_support( File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 187, in wrapper return func(*args, **kwargs) File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 1724, in precision_recall_fscore_support labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label) File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 1501, in _check_set_wise_labels y_type, y_true, y_pred = _check_targets(y_true, y_pred) File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 86, in _check_targets type_pred = type_of_target(y_pred, input_name="y_pred") File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 383, in type_of_target _assert_all_finite(data, input_name=input_name) File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/validation.py", line 122, in _assert_all_finite _assert_all_finite_element_wise( File "/home/user_3/.conda/envs/fuxian/lib/python3.8/site-packages/sklearn/utils/validation.py", line 171, in _assert_all_finite_element_wise raise ValueError(msg_err) ValueError: Input y_pred contains NaN. 你好，我在跑SMIS模型的时候遇到同样的问题，我该怎样去解决，这个是sklearn包的问题吗，我用的sklearn版本是1.3.2

**Comment by waveLi10** [comment]
vision pretrain
---------------VisionPretrain---------------
/home/w/anaconda3/envs/lls/lib/python3.8/site-packages/torch/nn/modules/transformer.py:306: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")
Epoch:1|Loss:[tensor(nan, device='cuda:0', grad_fn=<MseLossBackward0>)]|: 100%|█
Traceback (most recent call last):
  File "/home/w/data/lls/ConFEDE/SIMS/main.py", line 22, in <module>
    Vtrain(check={'MAE':10000}, config=config)
  File "/home/w/data/lls/ConFEDE/SIMS/train/constrastive/Vtrain.py", line 61, in Vtrain
    result, result_loss = eval(model, metrics, train_data, device, config)
  File "/home/w/data/lls/ConFEDE/SIMS/train/constrastive/Vtrain.py", line 110, in eval
    eval_results = metrics.eval_sims_regression(truth, pred)
  File "/home/w/data/lls/ConFEDE/SIMS/util/metrics.py", line 68, in eval_sims_regression
    raise ValueError("Input contains NaN values.")
ValueError: Input contains NaN values.
你好，我在跑SIMS数据集，VisionPretrain时遇到NaN问题，请问有什么解决方法

**Comment by XpastaX** [comment]
> vision pretrain ---------------VisionPretrain--------------- /home/w/anaconda3/envs/lls/lib/python3.8/site-packages/torch/nn/modules/transformer.py:306: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance) warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}") Epoch:1|Loss:[tensor(nan, device='cuda:0', grad_fn=)]|: 100%|█ Traceback (most recent call last): File "/home/w/data/lls/ConFEDE/SIMS/main.py", line 22, in Vtrain(check={'MAE':10000}, config=config) File "/home/w/data/lls/ConFEDE/SIMS/train/constrastive/Vtrain.py", line 61, in Vtrain result, result_loss = eval(model, metrics, train_data, device, config) File "/home/w/data/lls/ConFEDE/SIMS/train/constrastive/Vtrain.py", line 110, in eval eval_results = metrics.eval_sims_regression(truth, pred) File "/home/w/data/lls/ConFEDE/SIMS/util/metrics.py", line 68, in eval_sims_regression raise ValueError("Input contains NaN values.") ValueError: Input contains NaN values. 你好，我在跑SIMS数据集，VisionPretrain时遇到NaN问题，请问有什么解决方法

应该和上面的情况一样，检查下python环境是否一致。确保不弹出warning
或者尝试在下面代码中加入 batch_first=True
https://github.com/XpastaX/ConFEDE/blob/8a351d836568f921cd3a1c17eebec3363efe0d9f/SIMS/model/net/constrastive/vision_encoder_finetune.py#L52C26-L52C49
看warning像是新版本中，该模块默认batch_first = false
<img width="852" alt="image" src="https://github.com/XpastaX/ConFEDE/assets/55173000/35138df3-8f47-491c-8495-03d93f02895c">

**Comment by XpastaX** [comment]
matplotlib==3.4.2
pytorch-metric-learning==0.9.99
pytorch-pretrained-bert==0.6.2
torch==1.8.1
torchaudio==0.8.1
torchsummary==1.5.1
torchvision==0.9.1
transformers==4.5.1
ujson==4.0.2

**Comment by waveLi10** [comment]
感谢回答，我已经设置batch_first=True，确实不弹出warning。
但是input还是为NaN,因为是服务器的显卡是4090，CUDA版本为12.2，如果按照你给出的torch版本在此环境中无法运行，因为服务器的显卡还有其他人使用，不方便更换CUDA版本，请问还有其他解决方法吗
vision pretrain
---------------VisionPretrain---------------
Epoch:1|Loss:[tensor(nan, device='cuda:0', grad_fn=<MseLossBackward0>)]|: 100%|█
Traceback (most recent call last):
  File "/home/w/data/lls/ConFEDE/SIMS/main.py", line 22, in <module>
    Vtrain(check={'MAE':10000}, config=config)
  File "/home/w/data/lls/ConFEDE/SIMS/train/constrastive/Vtrain.py", line 61, in Vtrain
    result, result_loss = eval(model, metrics, train_data, device, config)
  File "/home/w/data/lls/ConFEDE/SIMS/train/constrastive/Vtrain.py", line 110, in eval
    eval_results = metrics.eval_sims_regression(truth, pred)
  File "/home/w/data/lls/ConFEDE/SIMS/util/metrics.py", line 68, in eval_sims_regression
    raise ValueError("Input contains NaN values.")
ValueError: Input contains NaN values.

Process finished with exit code 1

**Comment by XpastaX** [comment]
> 感谢回答，我已经设置batch_first=True，确实不弹出warning。 但是input还是为NaN,因为是服务器的显卡是4090，CUDA版本为12.2，如果按照你给出的torch版本在此环境中无法运行，因为服务器的显卡还有其他人使用，不方便更换CUDA版本，请问还有其他解决方法吗 vision pretrain ---------------VisionPretrain--------------- Epoch:1|Loss:[tensor(nan, device='cuda:0', grad_fn=)]|: 100%|█ Traceback (most recent call last): File "/home/w/data/lls/ConFEDE/SIMS/main.py", line 22, in Vtrain(check={'MAE':10000}, config=config) File "/home/w/data/lls/ConFEDE/SIMS/train/constrastive/Vtrain.py", line 61, in Vtrain result, result_loss = eval(model, metrics, train_data, device, config) File "/home/w/data/lls/ConFEDE/SIMS/train/constrastive/Vtrain.py", line 110, in eval eval_results = metrics.eval_sims_regression(truth, pred) File "/home/w/data/lls/ConFEDE/SIMS/util/metrics.py", line 68, in eval_sims_regression raise ValueError("Input contains NaN values.") ValueError: Input contains NaN values.
> 
> Process finished with exit code 1

可以下载其他版本cuda后，手动设置CUDA版本：
export LD_LIBRARY_PATH=/path/cuda-12.1/lib64
export PATH=/path/cuda-12.1/bin:$PATH
同时设置cache位置可帮助减少系统盘占用：
export TORCH_EXTENSIONS_DIR=/path/CACHE
mkdir -p ${TORCH_EXTENSIONS_DIR}
export HF_HOME=/path/CACHE/
