### ISSUE TITLE
文件缺少

### ISSUE THREAD

**Issue by ztbestwish** [XpastaX/ConFEDE#9]
您好，我想问一下，所缺少的文件，可以提供吗
model loaded from:
ckpt/encoder_feabest_MAE_text_encoder.ckpt
ckpt/encoder_feabest_MAE_vision_encoder.ckpt
ckpt/encoder_feabest_MAE_audio_encoder.ckpt
Traceback (most recent call last):
  File "main-fusion.py", line 21, in <module>
    TVA_train_fusion('TVA_fusion', check=check,
  File "/root/autodl-tmp/MOSEI/train/constrastive/TVA_fusion_train.py", line 83, in TVA_train_fusion
    model.load_model(load_model, load_pretrain=load_pretrain)
  File "/root/autodl-tmp/MOSEI/model/net/constrastive/TVA_fusion.py", line 213, in load_model
    self.text_encoder.load_state_dict(torch.load(text_encoder_path, map_location=self.device))
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/encoder_feabest_MAE_text_encoder.ckpt'

**Comment by ztbestwish** [comment]
> 您好，我想问一下，所缺少的文件，可以提供吗 model loaded from: ckpt/encoder_feabest_MAE_text_encoder.ckpt ckpt/encoder_feabest_MAE_vision_encoder.ckpt ckpt/encoder_feabest_MAE_audio_encoder.ckpt Traceback (most recent call last): File "main-fusion.py", line 21, in TVA_train_fusion('TVA_fusion', check=check, File "/root/autodl-tmp/MOSEI/train/constrastive/TVA_fusion_train.py", line 83, in TVA_train_fusion model.load_model(load_model, load_pretrain=load_pretrain) File "/root/autodl-tmp/MOSEI/model/net/constrastive/TVA_fusion.py", line 213, in load_model self.text_encoder.load_state_dict(torch.load(text_encoder_path, map_location=self.device)) File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 699, in load with _open_file_like(f, 'rb') as opened_file: File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 231, in _open_file_like return _open_file(name_or_buffer, mode) File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 212, in **init** super(_open_file, self).**init**(open(name, mode)) FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/encoder_feabest_MAE_text_encoder.ckpt'

在跑mosei模型里，所缺失的三个文件
